version: '3.4'

services:
  rails:
    build:
      context: .
      args:
        RUBY_VERSION: '2.6.5'
        PG_MAJOR: '11'
        BUNDLER_VERSION: '2.0.2'
        NODE_MAJOR: '12'
    stdin_open: true
    tty: true
    tmpfs:
      - /app/tmp
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - DATABASE_POOL=5
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    ports:
      - 5432

volumes:
  postgres:
  bundle:
  rails_cache:
